CC           = gcc
TARGET_CC    = $(CROSS_COMPILE)$(CC)

CC_OPTS      =

_OPTIFLAGS   = -O2 -pipe
_OPTIFLAGS  += $(OPTIMIZE)

_WARNFLAGS ?=

CPPFLAGS  =
CFLAGS    = $(_WARNFLAGS)
LDFLAGS   = -Wl,-O1 -Wl,--as-needed

CC_OPTS += -fPIC
CC_OPTS += -std=c99
CC_OPTS += -D_POSIX_C_SOURCE=200809L

CC_OPTS  += $(CC_OPTS_EXTRA)
CPPFLAGS += $(CPPFLAGS_EXTRA)
CFLAGS   += $(CFLAGS_EXTRA)
LDFLAGS  += $(LDFLAGS_EXTRA)

_C_COMPILE_FLAGS = $(CC_OPTS) $(CPPFLAGS) $(CFLAGS) $(_OPTIFLAGS)

COMPILE_C = $(TARGET_CC) $(_C_COMPILE_FLAGS) -c
LINK_O = $(TARGET_CC) $(_C_COMPILE_FLAGS) $(LDFLAGS)
